#!/bin/bash

echo "Applying migration TrusteeNino"

echo "Adding routes to register.trustees.individual.routes"
echo "" >> ../conf/register.trustees.individual.routes
echo "GET        /trusteeNino                       controllers.register.trustees.individual.TrusteeNinoController.onPageLoad()" >> ../conf/register.trustees.individual.routes

echo "Adding messages to conf.messages"
echo "" >> ../conf/messages.en
echo "trusteeNino.title = trusteeNino" >> ../conf/messages.en
echo "trusteeNino.heading = trusteeNino" >> ../conf/messages.en

echo "Moving test files from generated-test/ to test/"
rsync -avm --include='*.scala' -f 'hide,! */' ../generated-test/ ../test/
rm -rf ../generated-test/

echo "Migration TrusteeNino completed"
