#!/bin/bash

echo "Applying migration CompanyDirectorNino"

echo "Adding routes to register.establishers.company.director.routes"

echo "" >> ../conf/register.establishers.company.director.routes
echo "GET        /companyDirectorNino                       controllers.register.establishers.company.director.CompanyDirectorNinoController.onPageLoad(mode: Mode = NormalMode)" >> ../conf/register.establishers.company.director.routes
echo "POST       /companyDirectorNino                       controllers.register.establishers.company.director.CompanyDirectorNinoController.onSubmit(mode: Mode = NormalMode)" >> ../conf/register.establishers.company.director.routes

echo "GET        /changeCompanyDirectorNino                       controllers.register.establishers.company.director.CompanyDirectorNinoController.onPageLoad(mode: Mode = CheckMode)" >> ../conf/register.establishers.company.director.routes
echo "POST       /changeCompanyDirectorNino                       controllers.register.establishers.company.director.CompanyDirectorNinoController.onSubmit(mode: Mode = CheckMode)" >> ../conf/register.establishers.company.director.routes

echo "Adding messages to conf.messages"
echo "" >> ../conf/messages.en
echo "messages__companyDirectorNino__title = companyDirectorNino" >> ../conf/messages.en
echo "messages__companyDirectorNino__heading = companyDirectorNino" >> ../conf/messages.en
echo "messages__companyDirectorNino__checkYourAnswersLabel = companyDirectorNino" >> ../conf/messages.en
echo "messages__companyDirectorNino__error__required = Please give an answer for companyDirectorNino" >> ../conf/messages.en

echo "Adding helper method to CheckYourAnswersHelper"
awk '/class/ {\
     print;\
     print "";\
     print "  def companyDirectorNino: Option[AnswerRow] = userAnswers.get(identifiers.register.establishers.company.director.CompanyDirectorNinoId) map {";\
     print "    x => AnswerRow(\"companyDirectorNino.checkYourAnswersLabel\", Seq(if(x) \"site.yes\" else \"site.no\"), true, controllers.register.establishers.company.director.routes.CompanyDirectorNinoController.onPageLoad(CheckMode).url)"; print "  }";\
     next }1' ../app/utils/CheckYourAnswersHelper.scala > tmp && mv tmp ../app/utils/CheckYourAnswersHelper.scala

echo "Moving test files from generated-test/ to test/"
rsync -avm --include='*.scala' -f 'hide,! */' ../generated-test/ ../test/
rm -rf ../generated-test/

echo "Migration CompanyDirectorNino completed"
